# Generated by Django 4.2.22 on 2025-09-15 10:35 WAT

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=2048)),
                ('short_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('click_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'urls',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['short_code'], name='urls_short_c_484089_idx'), models.Index(fields=['created_at'], name='urls_created_71be6f_idx'), models.Index(fields=['click_count'], name='urls_click_c_24db78_idx')],
            },
        ),
    ]
